@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sat Aug 03 19:55:23 +0200 2019
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto e82e4f3017b74b73ae5343b2a3ab2c64 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot gcd_msf_dp_behav xil_defaultlib.gcd_msf_dp -log elaborate.log"
call xelab  -wto e82e4f3017b74b73ae5343b2a3ab2c64 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot gcd_msf_dp_behav xil_defaultlib.gcd_msf_dp -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
