@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Fri Aug 02 16:41:44 +0200 2019
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 1c6801be6f994a3b8d7cfc1dc0f9199c --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot mux1bitTestbench_behav xil_defaultlib.mux1bitTestbench -log elaborate.log"
call xelab  -wto 1c6801be6f994a3b8d7cfc1dc0f9199c --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot mux1bitTestbench_behav xil_defaultlib.mux1bitTestbench -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
